<a href="https://colab.research.google.com/github/kushap26-eng/labwork/blob/main/Lab_Work_8_1_%7C_Python_AI_ML_DA_DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### **1. Introduction to NumPy**

#### **Task 1**: Import the NumPy library and print its version.

In [1]:
import numpy as np
print(np.__version__)

2.1.3


**Task 2**: Create a one-dimensional NumPy array of integers from 0 to 9 and print it.

In [3]:
arr = np.arange(10)
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Task 3**: Generate a two-dimensional NumPy array with random values and print its shape and data type.

In [7]:
array = np.random.rand(3,4)
print(array)
print("Shape: ",array.shape)
print("Data Type: ",array.dtype)

[[0.62785591 0.03354579 0.92834261 0.62136436]
 [0.23918072 0.27934559 0.98378238 0.59713065]
 [0.3402448  0.09565303 0.65266787 0.13244316]]
Shape:  (3, 4)
Data Type:  float64


**Task 4**: Create a NumPy array with 50 evenly spaced values between 0 and 10.

In [9]:
numbers = np.linspace(0,50,5)
print(numbers)

[ 0.  12.5 25.  37.5 50. ]


**Task 5**: Write a program to demonstrate the difference between a Python list and a NumPy array by performing element-wise addition on both.

In [12]:
# using list
list1 = [1,2,3]
list2 = [4,5,6]
list_result = list1 + list2
print("Addition of list(Concatation):",list_result)

# using numpy arrays
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
result = arr1 + arr2
print("Array result(Elementwise):",result)

Addition of list(Concatation): [1, 2, 3, 4, 5, 6]
Array result(Elementwise): [5 7 9]


---

#### **2. Creation of NumPy Arrays**

**Task 6**: Create a NumPy array of all zeros with a shape of (3, 4).

In [13]:
arr = np.zeros((3,4),dtype=int)
arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

**Task 7**: Create a NumPy array of all ones with a shape of (2, 5) and a data type of float.

In [14]:
arr = np.ones((2,5),dtype=float)
arr


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

**Task 8**: Use `arange()` to create a NumPy array containing numbers from 10 to 50 with a step of 5.

In [16]:
arr = np.arange(10,51,5)
arr


array([10, 15, 20, 25, 30, 35, 40, 45, 50])

**Task 9**: Generate a 3x3 identity matrix using NumPy.

In [17]:
arr = np.eye(3)
arr


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Task 10**: Create a 4x4 array filled with random integers between 1 and 20.

In [18]:
arr = np.random.randint(1,21,size=(4,4))
arr


array([[ 7,  6, 17, 11],
       [15, 10,  2,  5],
       [11,  1,  9, 18],
       [10,  9, 10, 15]])

---

#### **3. Indexing and Slicing of NumPy Arrays**

**Task 11**: Create a 1D NumPy array with values ranging from 1 to 15. Slice the array to extract elements from index 3 to 8.

In [24]:
arr = np.arange(1,16)
print("Array:",arr)
extract_arr = arr[2:8]
extract_arr

Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


array([3, 4, 5, 6, 7, 8])

**Task 12**: Generate a 3x3 matrix with values ranging from 1 to 9. Retrieve the element at the second row and third column.

In [29]:
# Write your answer from this cell onwards
arr1 = np.arange(1,10)

In [30]:
arr2=arr1.reshape((3,3))

In [31]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
print(arr2[1][2])

6


**Task 13**: Slice a 4x4 array to extract the last two rows and the last two columns.

In [41]:
arr = np.arange(1,17)
print("Array",arr)
arr1 = arr.reshape((4,4))
print("Array1:",arr1)
arr3 = arr1[-2:,-2:]
arr3

Array [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
Array1: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


array([[11, 12],
       [15, 16]])

**Task 14**: Create a 5x5 matrix of random integers between 10 and 50. Replace all elements in the first row with the value 100.

In [52]:
arr = np.random.randint(10,50,size=(5,5))
print("Original Matrix:")
print(arr)
arr[0,:] = 100
print("Modified Matrix: ")
arr

Original Matrix:
[[21 17 43 32 44]
 [42 34 31 40 11]
 [46 40 32 48 41]
 [12 42 13 25 45]
 [46 21 30 20 14]]
Modified Matrix: 


array([[100, 100, 100, 100, 100],
       [ 42,  34,  31,  40,  11],
       [ 46,  40,  32,  48,  41],
       [ 12,  42,  13,  25,  45],
       [ 46,  21,  30,  20,  14]])

**Task 15**: Create a 1D NumPy array of 10 elements. Use boolean indexing to filter out all values greater than 5.

In [54]:
arr = np.arange(1,11)
print(arr)
filter_array = arr[arr <= 5]
print("Filtered Array:")
print(filter_array)

[ 1  2  3  4  5  6  7  8  9 10]
Filtered Array:
[1 2 3 4 5]
