<a href="https://colab.research.google.com/github/kushap26-eng/labwork/blob/main/Lab_Work_8_3_%7C_Python_AI_ML_DA_DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Task 1.1: Basic Filtering**
#### Create a NumPy array `ages` with the following values: `[25, 30, 18, 35, 22, 40, 17]`.
#### Use boolean indexing to create a new array `adults` containing only the ages that are 18 or older.


### **Task 1.2: Filtering with Multiple Conditions**
#### Using the `ages` array again, find the ages that are strictly greater than 20 AND strictly less than 35.
#### Store the result in a new array called `young_adults`.


### **Task 1.3: Filtering Strings**
#### Create a NumPy array `names` with the following values: `['Alice', 'Bob', 'Charlie', 'David', 'Eve']`.
#### Use boolean indexing to select names that start with the letter 'A' or 'E'.
#### Hint: You might need to use string operations within your boolean condition.

---

### **Task 2.1: Basic Masking for Selection**
#### Create a NumPy array `temperatures` with the following values: `[28, 32, 25, 35, 30, 22, 38]`.
#### Create a boolean mask `is_hot` where `True` indicates temperatures above 30 degrees Celsius.
#### Use this mask to select the hot temperatures from the `temperatures` array.


### **Task 2.2: Masking for Modification**
#### Using the `temperatures` array again, use the `is_hot` mask to change all temperatures above 30 degrees Celsius to 31 degrees Celsius.


### **Task 2.3: Using `np.where()` for Masking**
#### Create a NumPy array `scores` with the following values: `[65, 80, 72, 90, 55, 78]`.
#### Use `np.where()` to create a new array `grades`. If a score is 75 or above, the grade should be 'Pass', otherwise 'Fail'.

---

### **Task 3.1: Reshaping a 1D array to 2D**
#### Create a 1D NumPy array `numbers_1d` with values from 1 to 12 (inclusive).
#### Reshape this array into a 2D array with 3 rows and 4 columns.

### **Task 3.2: Reshaping a 2D array to 1D (Flattening)**
#### Using the `numbers_2d` array from the previous task, flatten it back into a 1D array.

### **Task 3.3: Reshaping with `-1`**
#### Create a 1D NumPy array `values` with values from 1 to 15 (inclusive).
#### Reshape this array into a 2D array with 5 rows, letting NumPy automatically determine the number of columns.

---

### **Task 4.1: Broadcasting a Scalar to an Array**
#### Create a NumPy array `prices` with the following values: `[10, 20, 30]`.
#### Increase all prices by 5 using broadcasting.

### **Task 4.2: Broadcasting a 1D Array to a 2D Array (Row-wise)**
#### Create a 2D NumPy array `sales` representing sales figures for 3 products over 2 days:
#### ```
#### [[10, 20],
####  [15, 25],
####  [12, 18]]
#### ```
#### Create a 1D NumPy array `bonuses` representing bonuses for each product: `[2, 3, 1]`.
#### Add the `bonuses` array to the `sales` array, broadcasting row-wise.


### **Task 4.3: Broadcasting a 1D Array to a 2D Array (Column-wise)**
#### Using the `sales` array again, create a 1D NumPy array `tax_rates` representing tax rates for each day: `[0.1, 0.05]`.
#### Calculate the tax amount for each sale by multiplying the `sales` array with the `tax_rates` array, broadcasting column-wise.

In [3]:
#Task 1.1
import numpy as np

ages = np.array([25,30,18,35,22,40,17])

adults = ages[ages >=18]
print("Original ages: ",ages)
print("Adults: ",adults)

Original ages:  [25 30 18 35 22 40 17]
Adults:  [25 30 18 35 22 40]


In [5]:
#Task 1.2
import numpy as np

ages = np.array([25,30,18,35,22,40,17])

young_adults = ages[(ages > 20) & (ages < 35)]
print(ages)
print("Young adults: ",young_adults)

[25 30 18 35 22 40 17]
Young adults:  [25 30 22]


In [7]:
#Task1.3
import numpy as np

names = np.array(['Alice','Bob','Charlie','David','Eve'])
mask = np.char.startswith(names,'A') | np.char.startswith(names,'E')
a_or_E = names[mask]

print("Original names: ",names)
print("Names starting with 'A' or 'E': ",a_or_E)


Original names:  ['Alice' 'Bob' 'Charlie' 'David' 'Eve']
Names starting with 'A' or 'E':  ['Alice' 'Eve']


In [9]:
#Task 2.1
import numpy as np
temerature = np.array([28,32,25,35,30,22,38])
is_hot = temerature > 30
hot_temparatures = temerature[is_hot]
print("Original temparature: ",temerature)
print("Boolean mask: ",is_hot)
print("Hot temparature:   ",hot_temparatures)

Original temparature:  [28 32 25 35 30 22 38]
Boolean mask:  [False  True False  True False False  True]
Hot temparature:    [32 35 38]


In [12]:
#Task2.2
import numpy as np

temerature = np.array([28,32,25,35,30,22,38])
is_hot = temerature > 30
temerature[is_hot] = 31
print("Modified temparature: ",temerature)

Modified temparature:  [28 31 25 31 30 22 31]


In [13]:
#Task 2.3
import numpy as np

scores = np.array([65,80,72,90,55,78])
grades = np.where(scores >= 75, "Pass","Fail")
print("Scores: ",scores)
print("Grades: ",grades)

Scores:  [65 80 72 90 55 78]
Grades:  ['Fail' 'Pass' 'Fail' 'Pass' 'Fail' 'Pass']


In [14]:
#Task 3.1
import numpy as np

numbers_1D = np.arange(1,13)
numbers_2D = numbers_1D.reshape(3,4)
print("1D Array:",numbers_1D)
print("2D Array: ",numbers_2D)

1D Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
2D Array:  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [20]:
#Task 3.2
import numpy as np

numbers_2D = np.random.randint(1,12,size=(3,4))
flatten_array = numbers_2D.flatten()

print("2D array: ",numbers_2D)
print("Flatten Array: ",flatten_array)

2D array:  [[ 3  6  7  2]
 [ 7  1 11  9]
 [ 8  6  3  2]]
Flatten Array:  [ 3  6  7  2  7  1 11  9  8  6  3  2]


In [21]:
#Task 3.3
values = np.arange(1,16)
values_2D = values.reshape(5,-1)
print("1D Array: ",values)
print("2D Array(5rows,automatic columns): \n",values_2D)
print("Shape of new array: ",values_2D.shape)

1D Array:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
2D Array(5rows,automatic columns): 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
Shape of new array:  (5, 3)


In [22]:
#Task 4.1
import numpy as np
prices = np.array([10,20,30])
updated_prices = prices + 5
print("Original prices: ",prices)
print("Updated prices: ",updated_prices)

Original prices:  [10 20 30]
Updated prices:  [15 25 35]


In [26]:
#Task 4.2

sales = np.array([[10,20],[12,18],[50,60]])
bonuses = np.array([2,3,1])
new_sales = sales + bonuses.reshape(3,1)
print("New Sales",new_sales)



New Sales [[12 22]
 [15 21]
 [51 61]]


In [27]:
# task 4.3
sales = np.array([[10,20],[15,25],[12,18]])
tax_rate = np.array([0.1,0.05])
tax_amt = sales *tax_rate
print("Tax Amount:",tax_amt)

Tax Amount: [[1.   1.  ]
 [1.5  1.25]
 [1.2  0.9 ]]
