<a href="https://colab.research.google.com/github/kushap26-eng/labwork/blob/main/Lab_Work_8_2_%7C_Python_AI_ML_DA_DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### **1. Mathematical Operations**

##### 1. Create two NumPy arrays of shape (3, 3) and perform element-wise addition, subtraction, multiplication, and division.

In [1]:
import numpy as np
array1 = np.random.randint(1,100,size=(3,3))
array2 = np.random.randint(1,100,size=(3,3))

print("Original Array1: ",array1)
print("Original Array2: ",array2)
print("Addition: ",array1+array2)
print("Subtraction: ",array1-array2)
print("Multiplication: ",array1*array2)
print("Division: ",array1/array2)


Original Array1:  [[68 74  9]
 [52 63 54]
 [55 32 66]]
Original Array2:  [[39 17 87]
 [73 64 66]
 [33 12 85]]
Addition:  [[107  91  96]
 [125 127 120]
 [ 88  44 151]]
Subtraction:  [[ 29  57 -78]
 [-21  -1 -12]
 [ 22  20 -19]]
Multiplication:  [[2652 1258  783]
 [3796 4032 3564]
 [1815  384 5610]]
Division:  [[1.74358974 4.35294118 0.10344828]
 [0.71232877 0.984375   0.81818182]
 [1.66666667 2.66666667 0.77647059]]


##### 2. Generate a NumPy array with random integers and apply square root, exponential, and logarithmic functions.

In [ ]:
import numpy as np
array = np.random.randint(1,50,5)
sqrt_arr = np.sqrt(array)
exp_arr = np.exp(array)
log_arr = np.log(array)
print("Original Array: \n",array)
print("\nSquare Root: \n",np.round(sqrt_arr,4))
print("\nExponential: \n",np.round(exp_arr,4))
print("\nNatural Logarithm: \n",np.round(log_arr,4))


Original Array: 
 [ 8 23 23 47 28]

Square Root: 
 [2.8284 4.7958 4.7958 6.8557 5.2915]

Exponential: 
 [2.98095800e+03 9.74480345e+09 9.74480345e+09 2.58131289e+20
 1.44625706e+12]

Natural Logarithm: 
 [2.0794 3.1355 3.1355 3.8501 3.3322]


##### 3. Create a NumPy array and apply trigonometric operations like sin, cos, and tan.

In [ ]:
import numpy as np
angles_degree = np.array([0,30,45,60,90])
print("Original Angles(Degrees): ",angles_degree)

angles_radians = np.radians(angles_degree)
print("Angles(Radians): ",angles_radians)

sine_values = np.sin(angles_radians)
cos_values = np.cos(angles_radians)
tangent_values = np.tan(angles_radians)

print("Sine: ",sine_values)
print("Cos:",cos_values)
print("Tangent:",tangent_values)

Original Angles(Degrees):  [ 0 30 45 60 90]
Angles(Radians):  [0.         0.52359878 0.78539816 1.04719755 1.57079633]
Sine:  [0.         0.5        0.70710678 0.8660254  1.        ]
Cos: [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
Tangent: [0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


##### 4. Normalize a NumPy array using vectorized operations (subtract mean and divide by std).

In [2]:
import numpy as np
array = np.array([10,20,30,40,50])
mean = np.mean(array)
std = np.std(array)
normalised = (array - mean) / std
print("Original Array:",array)
print("Mean:",mean)
print("Standard Deviation: ",std)
print("Normalised Array: ",normalised)


Original Array: [10 20 30 40 50]
Mean: 30.0
Standard Deviation:  14.142135623730951
Normalised Array:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


##### 5. Implement a function using NumPy that calculates the Euclidean distance between two points.

In [7]:
import numpy as np
def euclidean_distance(point1,point2):
  pont1 = np.array(point1)
  point2 = np.array(point2)
  distance = np.sqrt(np.sum((point1-point2)**2))

  return distance

p1 = list(map(float,input("Enter coordination of first point: ").split()))
p2 = list(map(float,input("Enter coordination of second point: ").split()))

out  = euclidean_distance(p1,p2)
print("Euclidean Distance: ",out)


Enter coordination of first point: 3 4
Enter coordination of second point: 0 0
Euclidean Distance:  5.0


#### **2. Combining and Splitting Arrays**

##### 1. Create two 1D arrays and concatenate them horizontally and vertically.

In [8]:
import numpy as np

arr1 = np.random.randint(1,10,3)
arr2 = np.random.randint(1,10,3)

horizontal = np.concatenate((arr1,arr2))
vertical = np.concatenate((arr1,arr2))

print("Array1: ",arr1)
print("Array2: ",arr2)

print("Horizontal Concatenation: ",horizontal)
print("Vertical Concatenation: ",vertical)

Array1:  [4 8 8]
Array2:  [2 2 6]
Horizontal Concatenation:  [4 8 8 2 2 6]
Vertical Concatenation:  [4 8 8 2 2 6]


##### 2. Stack multiple 2D arrays using vstack and hstack and then split them back using vsplit and hsplit.

In [15]:
import numpy as np
arr1 = np.random.randint(1,10,size=(2,2))
arr2 =np.random.randint(1,10,size=(2,2))
print("Array1:",arr1)
print("Array2:",arr2)

v_stake = np.vstack((arr1,arr2))
print("\nAfter vstake")
print(v_stake)

v_split = np.vsplit(v_stake,2)
print("\nAfter vsplit:")
for arr in v_split:
  print(arr)

h_stake= np.hstack((arr1,arr2))
print("\nAfter hstake")
print(h_stake)

h_split = np.hsplit(h_stake,2)
print("\nAfter hsplit:")
for arr in h_split:
  print(arr)

Array1: [[6 6]
 [8 8]]
Array2: [[3 6]
 [5 8]]

After vstake
[[6 6]
 [8 8]
 [3 6]
 [5 8]]

After vsplit:
[[6 6]
 [8 8]]
[[3 6]
 [5 8]]

After hstake
[[6 6 3 6]
 [8 8 5 8]]

After hsplit:
[[6 6]
 [8 8]]
[[3 6]
 [5 8]]


##### 3. Create a 2D array and split it into 4 equal sub-arrays.

In [17]:
import numpy as np

arr = np.arange(1,17).reshape(4,4)

print("Original Array: ")
print(arr)

result = np.vsplit(arr,4)
print("4 Equal Sub-arrays:")
for a in result:
  print(a)

Original Array: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
4 Equal Sub-arrays:
[[1 2 3 4]]
[[5 6 7 8]]
[[ 9 10 11 12]]
[[13 14 15 16]]


##### 4. Demonstrate the difference between concatenate, stack, and hstack functions using 2D arrays.

In [19]:
import numpy as np
arr1 = np.random.randint(1,10,size = (2,2))
arr2 = np.random.randint(1,10,size = (2,2))

print("Array1:")
print(arr1)

print("\nArray2: ")
print(arr2)

conc = np.concatenate((arr1,arr2),axis =0)
print("\nConcatenate: ")
print(conc)

st = np.stack((arr1,arr2),axis=0)
print("\nStack:")
print(st)

hs = np.hstack((arr1,arr2))
print("\nHstack:")
print(hs)

Array1:
[[5 6]
 [7 8]]

Array2: 
[[1 6]
 [3 5]]

Concatenate: 
[[5 6]
 [7 8]
 [1 6]
 [3 5]]

Stack:
[[[5 6]
  [7 8]]

 [[1 6]
  [3 5]]]

Hstack:
[[5 6 1 6]
 [7 8 3 5]]


##### 5. Create a 3D array and flatten it, then reshape it back to its original shape.

In [22]:
import numpy as np

arr = np.random.randint(1,10,size=(2,2,3))
print("Original Array: ")
print(arr)

print("\nFlatten Array: ",arr.flatten())

print("\nReshaped Array: ",arr.reshape(2,2,3))


Original Array: 
[[[8 2 6]
  [6 8 4]]

 [[8 2 8]
  [8 3 8]]]

Flatten Array:  [8 2 6 6 8 4 8 2 8 8 3 8]

Reshaped Array:  [[[8 2 6]
  [6 8 4]]

 [[8 2 8]
  [8 3 8]]]


#### **3. Search, Sort, Aggregating/Statistical Functions**

##### 1. Create a NumPy array and find the index of the maximum and minimum elements.

In [23]:
import numpy as np
arr = np.array([10,25,5,40,15])

print("Array:",arr)

max_index = np.argmax(arr)
min_index = np.argmin(arr)

print("Index of maximum element: ",max_index)
print("index of minimum element: ",min_index)


Array: [10 25  5 40 15]
Index of maximum element:  3
index of minimum element:  2


##### 2. Sort a 2D array along different axes and display the result.

In [28]:
import numpy as np

arr = np.random.randint(1,10,size=(3,3))

print("Original array:")
print(arr)

row_sort = np.sort(arr,axis=1)

print("\nSorted along rows:")
print(row_sort)

column_sort = np.sort(arr,axis=0)
print("\nSorted along columns:")
print(column_sort)

Original array:
[[2 6 4]
 [5 6 8]
 [4 3 9]]

Sorted along rows:
[[2 4 6]
 [5 6 8]
 [3 4 9]]

Sorted along columns:
[[2 3 4]
 [4 6 8]
 [5 6 9]]


##### 3. Generate a random NumPy array and find the mean, median, variance, and standard deviation.

In [32]:
import numpy as np

arr = np.random.randint(1,50,10)

print("Random Array: ")
print(arr)

print("Mean: ",np.mean(arr))
print("Median: ",np.median(arr))
print("Varaince: ",np.var(arr))
print("Standard Deviation: ",np.std(arr))

Random Array: 
[21 48 24 29  2 44 40 48 33  2]
Mean:  29.1
Median:  31.0
Varaince:  263.09000000000003
Standard Deviation:  16.22004932174992


##### 4. Use np.where to find all elements greater than a certain threshold in a given array.

In [34]:
import numpy as np
arr = np.array([10,25,5,40,15,30])
threhold = 20

result = np.where(arr>threhold)
print("Array: ",arr)
print("Threshold: ",threhold)
print("Elements greater than threshold: ",result)

Array:  [10 25  5 40 15 30]
Threshold:  20
Elements greater than threshold:  (array([1, 3, 5]),)


##### 5. Create a NumPy array and count how many elements are positive, negative, or zero.

In [35]:
import numpy as np
arr = np.array([10,-5,0,8,-2,0,15,-7])

print("Array: ",arr)

print("Positive elements: ",np.sum(arr>0))
print("Negative elements:",np.sum(arr<0))
print("Zero elements:",np.sum(arr==0))

Array:  [10 -5  0  8 -2  0 15 -7]
Positive elements:  3
Negative elements: 3
Zero elements: 2
